### PR TITLE
extended ags.json

### PR DESCRIPTION
**Pull request by ViktorGrosch**
data extended by latitude and longitude

### CODE REVIEW

**Comment by jgehrcke** [comment]
Nice! Happy to integrate that.

Quick question: which data source did you use for those values, and how did you try to minimize risk for human error when moving these numbers over? (Personally, I don't want to double-check all these numbers of course, and I would love to hear you argue for why you think these numbers are correct, w/o typos and other accidents :)).

**Comment by jgehrcke** [comment]
And what do you think about cutting to / rounding the decimal place to get rid of what's merely noise in the JSON doc? For example, assuming that 4 decimal places are enough : `50.9579243902439 -> 50.9579`.

**Comment by ViktorGrosch** [comment]
Most of the geo-data comes from OpenGeoDB (http://opengeodb.giswiki.org/wiki/OpenGeoDB_Downloads) and assigned by ags. I got most of the data for different districts of Berlin by hand from google maps. I carried out spot checks on google maps for assigned data.
Limiting the longitude and latitude data to 4 decimal digits would be sufficient at this point.

**Comment by jgehrcke** [comment]
> Most of the geo-data comes from OpenGeoDB (http://opengeodb.giswiki.org/wiki/OpenGeoDB_Downloads) and assigned by ags.

Gotcha, thanks!

> I got most of the data for different districts of Berlin by hand from google maps.

Thanks!

> I carried out spot checks on google maps for assigned data.

Lovely.

> Limiting the longitude and latitude data to 4 decimal digits would be sufficient at this point.

Thanks, again!

Merging now, please come back if you notice data issues -- relying on you here :-)

**Pull request merged**
